"""
Productivity & Documentation Exporter Tool for Jarvis Copilot.
Exports engineering reports, thermal loss calculations, and BOM summaries to formatted Markdown and JSON logs.
"""

import os
from langchain_core.tools import tool
import config

logger = config.get_logger(__name__)

@tool
def export_engineering_doc(
    title: str = "AutoPick Engineering Log",
    content: str = "Hardware audit summary content...",
    format_type: str = "markdown"
) -> str:
    """
    Exports structured engineering logs, thermal calculations, or audit summaries to docs/ directory.
    
    Args:
        title: Document title (e.g. "AutoPick Motor Driver Thermal Audit").
        content: Raw markdown or text content to export.
        format_type: Output format ("markdown" or "json").
    """
    os.makedirs("docs", exist_ok=True)
    clean_filename = title.lower().replace(" ", "_").replace("/", "_") + (".md" if format_type == "markdown" else ".json")
    filepath = os.path.join("docs", clean_filename)

    doc_banner = [
        f"# 📄 {title}",
        f"**Project**: AutoPick Robotic Arm (Multiverse AI)",
        f"**Generated By**: Jarvis PCB Copilot",
        "",
        "---",
        "",
        content
    ]

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(doc_banner))
        return f"Successfully exported engineering log to file:///{os.path.abspath(filepath)}"
    except Exception as e:
        return f"Error exporting engineering log: {e}"
