"""
Productivity & Documentation Exporter Tool for Jarvis Copilot.
Exports engineering reports, thermal loss calculations, and BOM summaries to formatted Markdown and JSON logs.
Returns structured dictionaries adhering to the {status, data, summary} contract.
"""

import os
from typing import Dict, Any
from langchain_core.tools import tool
import config

logger = config.get_logger(__name__)


@tool
def export_engineering_doc(
    title: str = "AutoPick Engineering Log",
    content: str = "Hardware audit summary content...",
    format_type: str = "markdown"
) -> dict:
    """
    Exports structured engineering logs, thermal calculations, or audit summaries to docs/ directory.
    """
    try:
        os.makedirs("docs", exist_ok=True)
        clean_filename = title.lower().replace(" ", "_").replace("/", "_") + (".md" if format_type == "markdown" else ".json")
        filepath = os.path.join("docs", clean_filename)

        doc_banner = [
            f"# 📄 {title}",
            f"**Project**: AutoPick Robotic Arm (Multiverse AI)",
            f"**Generated By**: Jarvis PCB Copilot",
            "",
            "---",
            "",
            content
        ]

        abs_path = os.path.abspath(filepath)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(doc_banner))

        summary_str = f"Exported engineering log '{title}' to {abs_path}."

        return {
            "status": "success",
            "summary": summary_str,
            "data": {
                "title": title,
                "file_path": abs_path,
                "format_type": format_type
            }
        }
    except Exception as e:
        logger.error(f"[export_engineering_doc Error] {e}")
        return {
            "status": "error",
            "summary": f"Error exporting engineering log: {e}",
            "data": {"error": str(e)}
        }
